Repository mi6/ic-design-system, pull requests merged in 2022-12, with the labels that each got.

#120 chore(root): reviewing assets
  static/accessibility-statement-guidance.docx
  static/accessibility-statement-template.docx
  static/blank-accessibility-conformance-report-vpat-wcag-24rev.docx
  static/icds-accessibility-conformance-report-12-10-22.docx
Labels: documentation

#123 BUGFIX: Change the URL for the og:image
  src/assets/og-image.png
  src/components/Layout/index.tsx
Labels: type: bug 🐛

#105 Update issue templates
  .github/ISSUE_TEMPLATE/------suggest-a-development-implementation-improvement-.md
  .github/ISSUE_TEMPLATE/---report-a-bug.md
  .github/ISSUE_TEMPLATE/---suggest-a-design-improvement-.md
Labels: type: big picture, dx
