Repository mi6/ic-design-system, pull requests merged in 2023-02, with the labels that each got.

#271 [Release]: Guidance site update with 2.1.0-beta.5 libraries
  package-lock.json
  package.json
Labels: type: release 🚀

#278 Update percentage of people who are neurodiverse in the accessibility section
  src/content/structured/accessibility/introduction.mdx
Labels: type: docs

#284 build(root): updated package.json to include new released libraries
  package-lock.json
  package.json
Labels: type: docs, dx

#305 docs(root): updated prism highlighter to use jsx instead of tsx
  src/components/CodePreview/index.tsx
  src/content/structured/components/hero/code.mdx
Labels: type: bug 🐛, dx

#307 chore(root): update vulnerable packages
  package-lock.json
Labels: dx

#317 [github-action]: Bugfix/6 concurrency update
  .github/workflows/ic-design-system-branches.yml
Labels: dx

#311 fix(root): updated side nav example
  src/content/structured/components/chips/code.mdx
  static/ic-side-nav-fixed-example/index.html
Labels: dx, side navigation component
