Repository mi6/ic-design-system, pull requests merged in 2023-01, with the labels that each got.

#209 refactor(root): update and fix issues with data entity previews / examples
  src/content/structured/components/data-entity/code.mdx
Labels: type: docs, component: data entity

#247 fix(root): updated qa link due to gh-pages update
  .github/workflows/add-qa-link-to-issues.yml
Labels: type: bug 🐛, development, dx

#246 docs(root): documentation about testing with RTL
  src/content/structured/get-started/custom-theme.mdx
  src/content/structured/get-started/testing-with-jest.mdx
  src/content/structured/get-started/testing-with-react-testing-library.mdx
Labels: type: docs, dx
